[package]
name = "clipboard-sync"
version = "0.1.0"
authors = ["Tomas Jakstas <tom.jakstas@gmail.com>"]
edition = "2018"
description = "Secure clipboard sync across your devices"
homepage = "https://github.com/songokas/clipboard-sync"
repository = "https://github.com/songokas/clipboard-sync"
license = "LICENSE"

[dependencies]
clipboard = "0.5"
chacha20poly1305 = "0.7"
base64 = "0.13.0"
chrono = "0.4"
rand = "0.7"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
futures = "0.3"
clap = {version = "2.27", features = ["yaml"]}
tokio = { version = "0.3", features = ["full"] }
tokio-test = "~0.3.0"
log = "~0.4.0"
env_logger = "~0.7.0"
flate2 = "1.0"
walkdir = "2"
dirs = "3.0"
cached = "0.22.0"

[dependencies.quinn]
version = "0.6.1"
optional = true

[dependencies.quiche]
version = "0.6.0"
optional = true

[features]
default = ["frames", "quic"]
quic = ["quiche"]
frames = []

[package.metadata.deb]
maintainer = "Tomas Jakstas <tom.jakstas@gmail.com>"
copyright = "2020, Tomas Jakstas <tom.jakstas@gmail.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
Secure clipboard synchronization accross your devices\
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/clipboard-sync", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
]
maintainer-scripts = "debian/"
systemd-units = { enable = false }