[package]
name = "clipboard-sync"
version = "0.1.0"
authors = ["Tomas Jakstas <tom.jakstas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5"
chacha20poly1305 = "0.7"
base64 = "0.13.0"
chrono = "0.4"
rand = "0.7"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
futures = "0.3"
clap = {version = "2.27", features = ["yaml"]}
tokio = { version = "0.3", features = ["full"] }
log = "~0.4.0"
env_logger = "~0.7.0"
flate2 = "1.0"
walkdir = "2"
