# [target.aarch64-unknown-linux-gnu]
# image = "clipboard-sync/aarch:latest"
# [target.i686-unknown-linux-gnu]
# image = "clipboard-sync/linux:latest"
# [target.x86_64-unknown-linux-gnu]
# image = "clipboard-sync/linux:latest"
