bind_address: 0.0.0.0
bind_port: 83232

identity: virgis-su-virguciu

groups:
  home:
    key: 32342342
    allowed_hosts:
      - 192.168.0.153
      - 192.168.0.54/23
  wide: 
    key: 32426536456
    # copy: ctrl+c default
    # paste: ctrl+v default
    # allowed_hosts default local network multicast

# clipboard-sync --allowed-host 192.168.0.1:83332 --group test --copy "ctrl+c" --paste "ctrl+p" --key $(< "key")